/**
 * Shared coverage configuration (PRD R6).
 *
 * Every vitest config (unit, browser-free, browser-extra, e2e-local-assets)
 * extends this so the four harnesses produce one merge-able coverage tree.
 * Each harness writes to its own `coverage/<harness>/` directory; the root
 * `pnpm coverage` script merges them via vitest's `--merge-coverage` flag.
 *
 * `src/react/react.ts` is a hook-only module measured ONLY by the browser
 * harness (it is in UNIT_ONLY_COVERAGE_EXCLUDES): the unit run can't render a
 * hook, so instrumenting it there only produces phantom 0-hit records that the
 * v8 by-url merge can't reliably reconcile. `src/three/three.ts` runs headless
 * (pure three.js math, no DOM) so it stays measured by both harnesses. The
 * merged report is what we ratchet against (A8, E0-E10).
 */
import type { CoverageOptions } from 'vitest/node';

/**
 * Files genuinely excluded from coverage measurement (config, types,
 * barrels — they have no logic to cover).
 */
export const COVERAGE_EXCLUDES = [
  'node_modules',
  'dist',
  'coverage',
  '**/*.config.ts',
  '**/*.config.js',
  '**/index.ts', // re-export barrels; no behavior of their own
  'src/simulation/simulation.ts', // re-export shim post-D3 (same shape as index.ts)
  'src/types/**', // type-only modules
  'src/asset-source/source.ts', // type-only: AssetSource interface + render-request unions (no runtime)
  'src/manifest/free.ts', // autogenerated literal
  'tests/**', // test files; co-located __tests__ excluded below
  '**/__tests__/**',
  '**/__screenshots__/**',
  'examples/**', // moved to tests/ in R4
];

/**
 * Floor coverage thresholds enforced as a ratchet (PRD A8).
 *
 * These are the measured unit-harness baseline (2026-05-26) at floor 1 %
 * below the actual numbers so a single skipped flaky line doesn't break
 * the build, but anything resembling a regression does. The E0-E10 sub-epic
 * raises these progressively to 100/100/100/100; every commit that closes
 * a coverage gap should ratchet the floor up in the same commit. Set
 * `thresholdAutoUpdate: true` once the merged tree is stable so vitest
 * does the ratchet automatically.
 */
export const MERGED_COVERAGE_THRESHOLDS = {
  // Threshold ratchet uses the CI-measured merged unit + browser-free floor.
  // Final React cleanup local merged proof: S=100, B=100, F=100, L=100.
  statements: 100,
  branches: 100,
  functions: 100,
  lines: 100,
};

export const HARNESS_COVERAGE_THRESHOLDS = {
  // Direct Vitest enforcement is unit-only; browser-only React/Three paths are
  // enforced by the merged gate above after browser-free coverage is collected.
  statements: 98,
  branches: 98.8,
  functions: 96.5,
  lines: 98,
};

/**
 * Build a coverage configuration scoped to a single harness's output
 * directory. The harness name becomes the sub-dir; merging combines them.
 * Thresholds are applied only when `HEX_WORLDS_COVERAGE_ENFORCE=1`
 * is set, so the default per-harness run doesn't block on the unit
 * floor (browser/e2e harnesses don't exercise every src/ file on their
 * own — only the merged tree should be threshold-checked).
 */
/**
 * The R3F render bridge `objects.ts` (a v8-ignored R3F component) and
 * `objects-sync.ts` (its R3F-free, unit-tested logic) are excluded from BROWSER
 * coverage: the browser loads them via the element imports but never executes the
 * sync functions, emitting a phantom 0%-hit record that the by-url merge can't
 * reconcile. objects-sync stays unit-covered; objects.ts is v8-ignored.
 */
const BROWSER_ONLY_COVERAGE_EXCLUDES = [
  'src/react-elements/objects.ts',
  'src/react-elements/camera.ts', // R3F useCamera hook — v8-ignored; camera-apply.ts (pure) is unit-covered
  'src/react-elements/objects-sync.ts',
  // These pure-TS game-flow modules are 100% covered by the UNIT harness. The
  // browser-free harness only imports them transitively (via `../../src` barrel)
  // and never exercises the `: undefined` arm of their ternaries, so it emits a
  // phantom record. Because Vite's browser transform SHIFTS LINE NUMBERS (esbuild
  // + module wrapping), the phantom's branch loc drifts on BOTH column AND line —
  // defeating even merge-coverage's branchLineKey fallback — so the by-url merge
  // keeps it as a separate 0-hit entry that fails the 100% branch gate. Excluding
  // them from BROWSER coverage leaves only the unit's fully-covered records.
  // (These were previously covered in-browser by simple-rpg-visual.test.ts, which
  // moved to packages/examples; the library now owns their coverage via the unit
  // suite — tests/unit/game-flow-branch-coverage.test.ts.)
  'src/scenario/scenario.ts',
  'src/scenario/recipe.ts',
  'src/simulation/engine.ts',
  'src/commands/commands.ts',
  'src/gameboard/gameboard.ts',
];

/**
 * The React-rendering element modules are exercised only in the BROWSER harness
 * (they call React hooks / render). The UNIT harness includes src/** but never
 * renders them, so it emits phantom 0%-hit records. The merge is by-url and keys
 * functions by source location; for anonymous arrows (useMemo/useCallback
 * factories) v8-in-Node and v8-in-Chromium report slightly different columns, so
 * the unit's 0-hit `anonymous` and the browser's covered `anonymous` DON'T unify
 * — the merged tree keeps BOTH and the 0-hit one fails the gate. Excluding these
 * from UNIT coverage leaves only the browser's covered records. (react.ts and
 * three.ts are NOT excluded — they merge cleanly because their statements sit on
 * unique lines; these element modules can't, because the drift is in anonymous
 * FUNCTION locations, not statements, so the line-key fallback doesn't apply.)
 * `objects-sync.ts` is NOT here — it is R3F-free and unit-tested.
 */
const UNIT_ONLY_COVERAGE_EXCLUDES = [
  // The React hook module: every export is a hook (verified — no non-hook runtime
  // in the file), so it is exercised ONLY by the browser harness that renders it.
  // The unit run instruments it (it is inside `include: ['src/**']`) but never
  // renders a hook, emitting phantom 0-hit statement/branch records. Under the v8
  // coverage provider those phantoms don't reliably reconcile with the browser's
  // covered records in the by-url merge (the exact line/statement that phantoms
  // shifts with any edit — a whack-a-mole), so we exclude react.ts from the UNIT
  // harness entirely. Its real coverage comes from tests/browser/*. This makes the
  // file-header comment ("react.ts … measured only where DOM exists") literally true.
  'src/react/react.ts',
  'src/react-elements/context.ts',
  'src/react-elements/hex-world.ts',
  'src/react-elements/placements.ts',
  'src/react-elements/tileset.ts',
  'src/react-elements/hooks.ts',
];

export function harnessCoverage(harness: string): CoverageOptions {
  const enforce = process.env.HEX_WORLDS_COVERAGE_ENFORCE === '1';
  const isBrowser = harness.startsWith('browser');
  const exclude = isBrowser
    ? [...COVERAGE_EXCLUDES, ...BROWSER_ONLY_COVERAGE_EXCLUDES]
    : [...COVERAGE_EXCLUDES, ...UNIT_ONLY_COVERAGE_EXCLUDES];
  return {
    provider: 'v8',
    enabled: process.env.HEX_WORLDS_COVERAGE === '1',
    reporter: ['json', 'lcov', 'text'],
    reportsDirectory: `./coverage/${harness}`,
    include: ['src/**/*.ts', 'scripts/**/*.ts'],
    exclude,
    clean: false, // do not wipe sibling harness output
    cleanOnRerun: false,
    thresholds: enforce ? HARNESS_COVERAGE_THRESHOLDS : undefined,
  };
}
