/**
 * Generate `docs-site/src/content/docs/guides/cli-reference.md` from the live
 * CLI `--help` output (PRD F-Site-6).
 *
 * Why a generator: the CLI's `usage()` block in `src/cli/cli.ts` is the
 * source of truth for what the binary actually accepts. Hand-maintaining a
 * parallel reference page drifts; auto-generating means a docs build always
 * matches the current CLI surface. Wire into CI via `pnpm docs-site:build`
 * (the docs-site CI job runs this script before the Astro build).
 */

import { execFileSync } from 'node:child_process';
import { existsSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

type ExecHelp = (
  file: string,
  args: string[],
  options: { cwd: string; encoding: BufferEncoding }
) => string;

type WriteTextFile = (path: string, contents: string, encoding: BufferEncoding) => void;

interface GenerateCliReferenceOptions {
  repoRoot?: string;
  outputPath?: string;
  execFileSyncImpl?: ExecHelp;
  writeFileSyncImpl?: WriteTextFile;
  log?: (message: string) => void;
}

interface GenerateCliReferenceResult {
  outputPath: string;
  contents: string;
}

interface ResolvedGenerateCliReferenceOptions {
  repoRoot: string;
  outputPath: string;
  execHelp: ExecHelp;
  writeTextFile: WriteTextFile;
  log: (message: string) => void;
}

export function defaultRepoRoot(): string {
  // docs-site/ lives at the WORKSPACE root, but this script is at
  // packages/declarative-hex-worlds/scripts/. Walk up to the directory holding
  // pnpm-workspace.yaml so the CLI reference lands in the real docs-site.
  let dir = import.meta.dirname;
  for (let i = 0; i < 12; i++) {
    if (existsSync(resolve(dir, 'pnpm-workspace.yaml'))) return dir;
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  // Fallback: the package root (pre-workspace layout).
  return resolve(import.meta.dirname, '..');
}

export function cliReferenceOutputPath(repoRoot = defaultRepoRoot()): string {
  return resolve(repoRoot, 'docs-site/src/content/docs/guides/cli-reference.md');
}

export function buildCliReference(helpOutput: string): string {
  return `---
title: CLI Reference
description: Every command, flag, and option accepted by the declarative-hex-worlds CLI binary.
sidebar:
  order: 1
---

import { Aside } from '@astrojs/starlight/components';

<Aside type="note">
This page is autogenerated from \`src/cli/cli.ts\` by \`scripts/generate-cli-reference.ts\`.
Edits land in the source, not here.
</Aside>

The library ships a Node CLI binary named \`declarative-hex-worlds\`. Invoke via \`pnpm exec declarative-hex-worlds <command>\` or \`npx declarative-hex-worlds <command>\`.

## Bootstrap first

Most commands operate against a local FREE or EXTRA pack tree. Before any tile / asset command, run:

\`\`\`bash
pnpm exec declarative-hex-worlds bootstrap
\`\`\`

This downloads the KayKit FREE pack and mirrors it flat under \`./models/\` (default). See the [bootstrap guide](/guides/bootstrap/) for source modes, integrity verification, and customizing the output directory.

## Full usage

\`\`\`
${helpOutput.trim()}
\`\`\`

## Common command recipes

### Doctor

Report local source + docs status. Useful first-time setup sanity check:

\`\`\`bash
declarative-hex-worlds doctor
\`\`\`

### Validate a FREE pack

\`\`\`bash
declarative-hex-worlds validate --edition free --source ./references/KayKit_Medieval_Hexagon_Pack_1.0_FREE
\`\`\`

### Compile a blueprint to a plan + scenario

\`\`\`bash
declarative-hex-worlds blueprint \\
  --blueprint ./blueprint.json \\
  --outScenario ./scenario.json \\
  --includeScenario
\`\`\`

### Run a simulation script

\`\`\`bash
declarative-hex-worlds simulate-scenario \\
  --scenario ./scenario.json \\
  --script ./simulation.script.json \\
  --rounds 10
\`\`\`

### Emit coverage ledger

\`\`\`bash
declarative-hex-worlds coverage \\
  --checksPassed \\
  --outJson docs/release-readiness.json \\
  --outMarkdown docs/release-readiness.md
\`\`\`

## Safe output paths

Every \`--out*\` flag goes through \`safeResolveOutput\` ([PRD C1](https://github.com/jbcom/declarative-hex-worlds/blob/main/docs/PRD/1.0.md#c1)). Paths that escape the current working directory throw before any write happens. \`extract\` refuses to wipe a non-empty destination unless \`--force\` is passed.

<Aside type="danger">
Setting \`HEX_WORLDS_OUT_ROOT\` to an absolute path widens the output jail beyond the working directory. Use only in controlled CI environments. Never set it to \`/\` or any ancestor of sensitive paths — the CLI will write there without further restrictions.
</Aside>

## JSON flag schemas and error contracts

Several flags accept JSON values directly or via a file path:

- **\`--pieceSourceRoots\`** — \`{ "sourceRoots": { "<packName>": "<absoluteOrRelativePath>" } }\`. Keys must match \`[A-Za-z0-9_:-]+\`; any key that is a prototype-pollution vector (\`__proto__\`, \`constructor\`, \`prototype\`) is rejected before the object is parsed.
- **\`--pieceOverrides\`** — \`{ "overrides": { "<pieceId>": { "footprint"?: ..., "criteria"?: ..., "tags"?: string[], "metadata"?: ... } } }\`.
- **\`--pieces\`** (all \`pieces*\` commands) — a path to a JSON file produced by \`pieces-from-assets\`. Not accepted as inline JSON.

All JSON parsing errors surface as \`GameboardCliError\` with a descriptive message on stderr. Exit code is always non-zero on error.

## Errors

CLI errors are \`GameboardCliError\` instances ([PRD D2](https://github.com/jbcom/declarative-hex-worlds/blob/main/docs/PRD/1.0.md#d2)). The library's error taxonomy is documented in the [errors reference](/reference/errors/).
`;
}

export function resolveGenerateCliReferenceOptions(
  options: GenerateCliReferenceOptions = {}
): ResolvedGenerateCliReferenceOptions {
  const repoRoot = options.repoRoot ?? defaultRepoRoot();
  return {
    repoRoot,
    outputPath: options.outputPath ?? cliReferenceOutputPath(repoRoot),
    execHelp: options.execFileSyncImpl ?? (execFileSync as ExecHelp),
    writeTextFile: options.writeFileSyncImpl ?? writeFileSync,
    log: options.log ?? console.log,
  };
}

export function generateCliReference(
  options: GenerateCliReferenceOptions = {}
): GenerateCliReferenceResult {
  const { repoRoot, outputPath, execHelp, writeTextFile, log } =
    resolveGenerateCliReferenceOptions(options);
  const helpOutput = execHelp(
    'pnpm',
    ['exec', 'tsx', 'src/cli/cli.ts', '--help'],
    {
      cwd: repoRoot,
      encoding: 'utf8',
    }
  );
  const contents = buildCliReference(helpOutput);
  writeTextFile(outputPath, contents, 'utf8');
  log(`Wrote ${outputPath}`);

  return { outputPath, contents };
}

export function isDirectRun(
  argvEntry = process.argv[1],
  moduleUrl = import.meta.url
): boolean {
  return argvEntry
    ? resolve(argvEntry).toLowerCase() === fileURLToPath(moduleUrl).toLowerCase()
    : false;
}

/* v8 ignore next 3 -- thin executable entrypoint; predicate and generator are unit-tested. */
if (isDirectRun()) {
  generateCliReference();
}
