import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    actors: 'src/actors.ts',
    blueprint: 'src/scenario/blueprint.ts',
    catalog: 'src/scenario/catalog.ts',
    compatibility: 'src/interop/compatibility.ts',
    commands: 'src/commands/index.ts',
    coverage: 'src/interop/coverage.ts',
    coordinates: 'src/coordinates/index.ts',
    gameboard: 'src/gameboard/index.ts',
    grid: 'src/coordinates/grid.ts',
    interop: 'src/interop/index.ts',
    koota: 'src/koota.ts',
    layout: 'src/coordinates/layout.ts',
    movement: 'src/movement.ts',
    navigation: 'src/gameboard/navigation.ts',
    occupancy: 'src/gameboard/occupancy.ts',
    patrol: 'src/patrol.ts',
    pieces: 'src/pieces/index.ts',
    projection: 'src/coordinates/projection.ts',
    quests: 'src/quests.ts',
    recipe: 'src/scenario/recipe.ts',
    registry: 'src/scenario/registry.ts',
    react: 'src/react.ts',
    'rule-types': 'src/rules/rule-types.ts',
    rules: 'src/rules/index.ts',
    runtime: 'src/runtime.ts',
    scenario: 'src/scenario/index.ts',
    selectors: 'src/selectors/index.ts',
    simulation: 'src/simulation/index.ts',
    systems: 'src/systems/index.ts',
    three: 'src/three.ts',
    traits: 'src/traits/index.ts',
    types: 'src/types/index.ts',
    validation: 'src/rules/validation.ts',
    'world-rules': 'src/systems/world-rules-system.ts',
    cli: 'src/cli.ts',
    ingest: 'src/ingest/index.ts',
    'manifest/free': 'src/manifest/free.ts',
    'manifest/schema': 'src/manifest/schema.ts',
    'examples/blueprint-board-usage': 'examples/blueprint-board-usage.ts',
    'examples/simple-rpg-usage': 'examples/simple-rpg-usage.ts',
  },
  format: ['esm'],
  dts: true,
  sourcemap: true,
  clean: true,
  target: 'es2022',
  // Shared chunks keep Koota trait identities stable when consumers mix package subpaths.
  splitting: true,
  esbuildOptions(options) {
    options.sourcesContent = false;
  },
  external: [
    '@jbcom/medieval-hexagon-gameboard',
    /^@jbcom\/medieval-hexagon-gameboard\//,
    'koota',
    'koota/react',
    'react',
    'three',
  ],
});
