/**
 * Shared coverage configuration (PRD R6).
 *
 * Every vitest config (unit, browser-free, browser-extra, e2e-local-assets)
 * extends this so the four harnesses produce one merge-able coverage tree.
 * Each harness writes to its own `coverage/<harness>/` directory; the root
 * `pnpm coverage` script merges them via vitest's `--merge-coverage` flag.
 *
 * `react.ts` + `three.ts` are excluded from unit coverage (Node lacks DOM)
 * but ARE measured by browser-free + browser-extra, so the merged report
 * is what we ratchet against (A8, E0-E10).
 */
import type { CoverageOptions } from 'vitest/node';

/**
 * Files genuinely excluded from coverage measurement (config, types,
 * barrels — they have no logic to cover).
 */
export const COVERAGE_EXCLUDES = [
  'node_modules',
  'dist',
  'coverage',
  '**/*.config.ts',
  '**/*.config.js',
  '**/index.ts', // re-export barrels; no behavior of their own
  'src/types/**', // type-only modules
  'src/manifest/free.ts', // autogenerated literal
  'tests/**', // test files; co-located __tests__ excluded below
  '**/__tests__/**',
  '**/__screenshots__/**',
  'examples/**', // moved to tests/ in R4
  'scripts/**', // build/audit scripts; tested via integration runs
];

/**
 * Build a coverage configuration scoped to a single harness's output
 * directory. The harness name becomes the sub-dir; merging combines them.
 */
export function harnessCoverage(harness: string): CoverageOptions {
  return {
    provider: 'v8',
    enabled: process.env.MEDIEVAL_HEXAGON_COVERAGE === '1',
    reporter: ['json', 'lcov', 'text'],
    reportsDirectory: `./coverage/${harness}`,
    include: ['src/**/*.ts'],
    exclude: COVERAGE_EXCLUDES,
    clean: false, // do not wipe sibling harness output
    cleanOnRerun: false,
  };
}
