/**
 * Shared coverage configuration (PRD R6).
 *
 * Every vitest config (unit, browser-free, browser-extra, e2e-local-assets)
 * extends this so the four harnesses produce one merge-able coverage tree.
 * Each harness writes to its own `coverage/<harness>/` directory; the root
 * `pnpm coverage` script merges them via vitest's `--merge-coverage` flag.
 *
 * `react.ts` + `three.ts` are excluded from unit coverage (Node lacks DOM)
 * but ARE measured by browser-free + browser-extra, so the merged report
 * is what we ratchet against (A8, E0-E10).
 */
import type { CoverageOptions } from 'vitest/node';

/**
 * Files genuinely excluded from coverage measurement (config, types,
 * barrels — they have no logic to cover).
 */
export const COVERAGE_EXCLUDES = [
  'node_modules',
  'dist',
  'coverage',
  '**/*.config.ts',
  '**/*.config.js',
  '**/index.ts', // re-export barrels; no behavior of their own
  'src/simulation/simulation.ts', // re-export shim post-D3 (same shape as index.ts)
  'src/types/**', // type-only modules
  'src/manifest/free.ts', // autogenerated literal
  'tests/**', // test files; co-located __tests__ excluded below
  '**/__tests__/**',
  '**/__screenshots__/**',
  'examples/**', // moved to tests/ in R4
];

/**
 * Floor coverage thresholds enforced as a ratchet (PRD A8).
 *
 * These are the measured unit-harness baseline (2026-05-26) at floor 1 %
 * below the actual numbers so a single skipped flaky line doesn't break
 * the build, but anything resembling a regression does. The E0-E10 sub-epic
 * raises these progressively to 100/100/100/100; every commit that closes
 * a coverage gap should ratchet the floor up in the same commit. Set
 * `thresholdAutoUpdate: true` once the merged tree is stable so vitest
 * does the ratchet automatically.
 */
export const COVERAGE_THRESHOLDS = {
  // CI runs without the references/ tree (it's gitignored — bootstrap is the
  // consumer story per Phase RB), so any `it.skipIf(!HAS_FREE_REFERENCES)`
  // test stays unexecuted. The threshold ratchet uses the CI floor — local
  // runs read higher because the skip-gated tests do execute against the
  // local references checkout.
  // Now that RB-CI runs the bootstrap step in CI, the references-gated
  // tests do execute on the runner — local + CI floors converge. Each
  // E0a/E0h commit advances these.
  statements: 64.1,
  branches: 62,
  functions: 75.3,
  lines: 63.7,
};

/**
 * Build a coverage configuration scoped to a single harness's output
 * directory. The harness name becomes the sub-dir; merging combines them.
 * Thresholds are applied only when `MEDIEVAL_HEXAGON_COVERAGE_ENFORCE=1`
 * is set, so the default per-harness run doesn't block on the unit
 * floor (browser/e2e harnesses don't exercise every src/ file on their
 * own — only the merged tree should be threshold-checked).
 */
export function harnessCoverage(harness: string): CoverageOptions {
  const enforce = process.env.MEDIEVAL_HEXAGON_COVERAGE_ENFORCE === '1';
  return {
    provider: 'v8',
    enabled: process.env.MEDIEVAL_HEXAGON_COVERAGE === '1',
    reporter: ['json', 'lcov', 'text'],
    reportsDirectory: `./coverage/${harness}`,
    include: ['src/**/*.ts', 'scripts/**/*.ts'],
    exclude: COVERAGE_EXCLUDES,
    clean: false, // do not wipe sibling harness output
    cleanOnRerun: false,
    thresholds: enforce ? COVERAGE_THRESHOLDS : undefined,
  };
}
