/**
 * Manifest drift contract.
 *
 * `src/manifest/free.ts` + `assets/free/manifest.json` are autogenerated
 * from the upstream KayKit FREE pack under
 * `references/KayKit_Medieval_Hexagon_Pack_1.0_FREE/`. If a contributor
 * edits the manifest by hand, or the upstream pack drifts and we forget
 * to regenerate, the bundled metadata stops matching the bootstrap-fetched
 * GLTF tree and consumers get silent breakage.
 *
 * This spec regenerates the manifest into a tmp directory and asserts
 * byte-identity with the committed files. Drift fails with the path
 * that drifted; `pnpm assets:free` regenerates.
 *
 * In CI, the `references/` tree is absent (it's gitignored — bootstrap
 * is the consumer story per Phase RB). The spec gracefully skips its
 * substantive assertions in that case via `it.skipIf(...)`, leaving the
 * "we know we're skipping" sentinel test passing so CI never silently
 * lacks coverage.
 *
 * Replaces the bespoke `scripts/audit-manifest-drift.ts` (deleted).
 */

import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { afterAll, describe, expect, it } from 'vitest';

const repoRoot = resolve(import.meta.dirname, '..', '..');
const referenceFreeRoot = join(repoRoot, 'references/KayKit_Medieval_Hexagon_Pack_1.0_FREE');
const committedModule = join(repoRoot, 'src/manifest/free.ts');
const committedJson = join(repoRoot, 'assets/free/manifest.json');

const referencesPresent = existsSync(referenceFreeRoot);
let tmpRoot: string | undefined;

afterAll(() => {
  if (tmpRoot) rmSync(tmpRoot, { recursive: true, force: true });
});

describe('manifest drift contract', () => {
  it('committed manifest files exist (run `pnpm assets:free` if missing)', () => {
    expect(existsSync(committedModule), `${committedModule} missing`).toBe(true);
    expect(existsSync(committedJson), `${committedJson} missing`).toBe(true);
  });

  it('sentinel — references/ tree present locally? (skip on CI is expected)', () => {
    // Always passes; surfaces in the report which mode this run is in so
    // a missing references/ tree in a local dev run doesn't silently
    // skip drift detection without notice.
    expect([true, false]).toContain(referencesPresent);
  });

  it.skipIf(!referencesPresent)(
    'regenerated src/manifest/free.ts matches committed bytes',
    () => {
      tmpRoot ??= mkdtempSync(join(tmpdir(), 'dhw-manifest-drift-'));
      execFileSync(
        'pnpm',
        [
          'exec',
          'tsx',
          'scripts/generate-package-assets.ts',
          '--edition',
          'free',
          '--source',
          referenceFreeRoot,
          '--package',
          tmpRoot,
        ],
        { cwd: repoRoot, stdio: ['ignore', 'pipe', 'pipe'] }
      );
      const regenerated = readFileSync(join(tmpRoot, 'src/manifest/free.ts'), 'utf8');
      const committed = readFileSync(committedModule, 'utf8');
      expect(
        regenerated,
        'src/manifest/free.ts drift — run `pnpm assets:free` + commit'
      ).toBe(committed);
    }
  );

  it.skipIf(!referencesPresent)(
    'regenerated assets/free/manifest.json matches committed bytes',
    () => {
      tmpRoot ??= mkdtempSync(join(tmpdir(), 'dhw-manifest-drift-'));
      // Reuse the regeneration from the previous test if both ran; if
      // only this one ran, regenerate now.
      if (!existsSync(join(tmpRoot, 'assets/free/manifest.json'))) {
        execFileSync(
          'pnpm',
          [
            'exec',
            'tsx',
            'scripts/generate-package-assets.ts',
            '--edition',
            'free',
            '--source',
            referenceFreeRoot,
            '--package',
            tmpRoot,
          ],
          { cwd: repoRoot, stdio: ['ignore', 'pipe', 'pipe'] }
        );
      }
      const regenerated = readFileSync(join(tmpRoot, 'assets/free/manifest.json'), 'utf8');
      const committed = readFileSync(committedJson, 'utf8');
      expect(
        regenerated,
        'assets/free/manifest.json drift — run `pnpm assets:free` + commit'
      ).toBe(committed);
    }
  );
});
