/**
 * `src/coordinates/layout-runtime.ts` — the koota-backed half of layout
 * generation (RFC 0001 RFC0-CORE).
 *
 * The pure layout surface (site inspection, fill analysis, placement generation
 * from a `GameboardPlan`) stays koota-free in `./layout` so it is `./core`-eligible.
 * The two functions that SPAWN generated placements into a live koota world —
 * `spawnGameboardLayoutPlacements` and `spawnGameboardLayoutFill` — plus the
 * world→plan projection they use, live here in the runtime tier.
 *
 * @module
 */
import type { Entity, World } from 'koota';
import { GameboardRuntimeError } from '../errors';
import type { GameboardPlan } from '../gameboard';
import {
  GameboardState,
  readGameboardPlacements,
  readGameboardTiles,
  spawnGameboardPlacement,
} from '../koota';
import {
  type GameboardLayoutFillOptions,
  type GameboardLayoutPlacementOptions,
  createGameboardLayoutFillPlacements,
  createGameboardLayoutPlacements,
} from './layout';

/** Project a live koota world to the plan shape the pure layout helpers consume. */
function projectWorldForLayout(world: World): GameboardPlan {
  const board = world.get(GameboardState);
  if (!board) {
    throw new GameboardRuntimeError('World does not contain GameboardState');
  }
  return {
    schemaVersion: board.schemaVersion as GameboardPlan['schemaVersion'],
    seed: board.seed,
    shape: { ...board.shape },
    textureSet: board.textureSet,
    tiles: readGameboardTiles(world),
    placements: readGameboardPlacements(world),
    warnings: [],
  };
}

/** Spawn generated layout placements into a Koota world. */
export function spawnGameboardLayoutPlacements(
  world: World,
  options: GameboardLayoutPlacementOptions
): Entity[] {
  return createGameboardLayoutPlacements(projectWorldForLayout(world), options).map((placement) =>
    spawnGameboardPlacement(world, placement)
  );
}

/** Spawn all placements generated by a layout fill pass into a Koota world. */
export function spawnGameboardLayoutFill(
  world: World,
  options: GameboardLayoutFillOptions
): Entity[] {
  return createGameboardLayoutFillPlacements(projectWorldForLayout(world), options).map(
    (placement) => spawnGameboardPlacement(world, placement)
  );
}
