/**
 * Packaged FREE KayKit Medieval Hexagon manifest, exported as typed runtime data.
 *
 * @remarks
 * The single source of truth is `assets/free/manifest.json` (generated by
 * `pnpm assets:free` and shipped in the published tarball's `files`). This
 * module is a thin, typed re-export of that JSON — NOT a second hand-
 * materialized copy. It was previously a 16.5k-line TS literal duplicating the
 * JSON byte-for-byte, which forced a 6 GB DTS-bundler heap and a drift test to
 * keep the twin copies in sync; RFC 0001 (G0) retired that. The eventual
 * direction is that ingest normalizes this KayKit manifest INTO the
 * source-agnostic `AssetSourceSpec`; this typed re-export is the interim.
 *
 * @module
 */
import freeManifestJson from '../../assets/free/manifest.json' with { type: 'json' };
import type { MedievalHexagonManifest } from '../types';

/**
 * Normalized manifest for the FREE KayKit Medieval Hexagon assets bundled in the npm package.
 *
 * @remarks
 * Eager export. Consumers that want lazy / async loading should prefer
 * {@link loadFreeManifest} instead — same data, Promise-wrapped, identity-stable.
 */
export const freeManifest: MedievalHexagonManifest =
  freeManifestJson as unknown as MedievalHexagonManifest;

/**
 * Async-first accessor for the FREE manifest.
 *
 * @remarks
 * The manifest is imported statically (bundled from the JSON), so this resolves
 * immediately — it exists to give async-first consumers a stable contract.
 * Identity-stable: every call resolves to the same reference as {@link freeManifest}.
 */
export async function loadFreeManifest(): Promise<MedievalHexagonManifest> {
  return freeManifest;
}

export default freeManifest;
