/**
 * Manifest drift gate (PRD A3b).
 *
 * The bundled `src/manifest/free.ts` + `assets/free/manifest.json` are
 * autogenerated from the upstream KayKit FREE pack under
 * `references/KayKit_Medieval_Hexagon_Pack_1.0_FREE/`. If a contributor
 * edits the manifest by hand, or the upstream pack drifts and we forget
 * to regenerate, the bundled metadata stops matching the bootstrap-fetched
 * GLTF tree and consumers get silent breakage.
 *
 * This script regenerates the manifest into a tmp directory and asserts
 * byte-identity with the committed files. Drift fails the gate with the
 * exact `git diff`.
 *
 * In CI, the `references/` tree is absent (it's gitignored — bootstrap is
 * the consumer story per Phase RB). The script detects that case and
 * exits 0 with a "skipped" notice; the gate becomes meaningful once the
 * bootstrap CLI lands and CI can fetch the upstream pack itself.
 */

import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

const repoRoot = resolve(import.meta.dirname, '..');
const referenceFreeRoot = join(repoRoot, 'references/KayKit_Medieval_Hexagon_Pack_1.0_FREE');
const committedModule = join(repoRoot, 'src/manifest/free.ts');
const committedJson = join(repoRoot, 'assets/free/manifest.json');

if (!existsSync(referenceFreeRoot)) {
  console.log(
    'manifest drift audit: skipped — references/ tree not present (expected in CI before Phase RB bootstrap lands).'
  );
  process.exit(0);
}

if (!existsSync(committedModule) || !existsSync(committedJson)) {
  console.error(
    'manifest drift audit: committed manifest files missing — run `pnpm assets:free` and commit the result.'
  );
  process.exit(1);
}

const tmpRoot = mkdtempSync(join(tmpdir(), 'mhg-manifest-drift-'));
try {
  execFileSync(
    'pnpm',
    [
      'exec',
      'tsx',
      'scripts/generate-package-assets.ts',
      '--edition',
      'free',
      '--source',
      referenceFreeRoot,
      '--package',
      tmpRoot,
    ],
    { cwd: repoRoot, stdio: ['ignore', 'pipe', 'pipe'] }
  );

  const regeneratedModule = join(tmpRoot, 'src/manifest/free.ts');
  const regeneratedJson = join(tmpRoot, 'assets/free/manifest.json');

  const committedModuleBytes = readFileSync(committedModule, 'utf8');
  const regeneratedModuleBytes = readFileSync(regeneratedModule, 'utf8');
  const committedJsonBytes = readFileSync(committedJson, 'utf8');
  const regeneratedJsonBytes = readFileSync(regeneratedJson, 'utf8');

  const drifts: string[] = [];
  if (committedModuleBytes !== regeneratedModuleBytes) {
    drifts.push('src/manifest/free.ts');
  }
  if (committedJsonBytes !== regeneratedJsonBytes) {
    drifts.push('assets/free/manifest.json');
  }

  if (drifts.length > 0) {
    console.error(
      `manifest drift audit: regenerated content differs from committed for: ${drifts.join(', ')}.`
    );
    console.error('Run `pnpm assets:free` and commit the updated files.');
    process.exit(1);
  }

  console.log('manifest drift audit passed (regenerated manifest matches committed bytes).');
} finally {
  rmSync(tmpRoot, { recursive: true, force: true });
}
