/**
 * Generate `docs-site/src/content/docs/guides/cli-reference.md` from the live
 * CLI `--help` output (PRD F-Site-6).
 *
 * Why a generator: the CLI's `usage()` block in `src/cli/cli.ts` is the
 * source of truth for what the binary actually accepts. Hand-maintaining a
 * parallel reference page drifts; auto-generating means a docs build always
 * matches the current CLI surface. Wire into CI via `pnpm docs-site:build`
 * (the docs-site CI job runs this script before the Astro build).
 */

import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const repoRoot = resolve(import.meta.dirname, '..');
const outputPath = resolve(repoRoot, 'docs-site/src/content/docs/guides/cli-reference.md');

const helpOutput = execFileSync('pnpm', ['exec', 'tsx', 'src/cli/cli.ts', '--help'], {
  cwd: repoRoot,
  encoding: 'utf8',
});

const banner = `---
title: CLI Reference
description: Every command, flag, and option accepted by the declarative-hex-worlds CLI binary.
sidebar:
  order: 1
---

import { Aside } from '@astrojs/starlight/components';

<Aside type="note">
This page is autogenerated from \`src/cli/cli.ts\` by \`scripts/generate-cli-reference.ts\`.
Edits land in the source, not here.
</Aside>

The library ships a Node CLI at \`declarative-hex-worlds\` (and the same binary as \`declarative-hex-worlds\` once installed). Invoke via \`pnpm exec declarative-hex-worlds <command>\` or \`npx declarative-hex-worlds <command>\`.

## Bootstrap first

Most commands operate against a local FREE or EXTRA pack tree. Before any tile / asset command, run:

\`\`\`bash
pnpm exec declarative-hex-worlds bootstrap
\`\`\`

This downloads the KayKit FREE pack and mirrors it under \`public/assets/models/addons/kaykit_medieval_hexagon_pack/Assets/gltf/\`. See the [bootstrap guide](/guides/bootstrap/) for source modes, integrity verification, and customizing the output directory.

## Full usage

\`\`\`
${helpOutput.trim()}
\`\`\`

## Common command recipes

### Doctor

Report local source + docs status. Useful first-time setup sanity check:

\`\`\`bash
declarative-hex-worlds doctor
\`\`\`

### Validate a FREE pack

\`\`\`bash
declarative-hex-worlds validate --edition free --source ./references/KayKit_Medieval_Hexagon_Pack_1.0_FREE
\`\`\`

### Compile a blueprint to a plan + scenario

\`\`\`bash
declarative-hex-worlds blueprint \\
  --blueprint ./blueprint.json \\
  --outScenario ./scenario.json \\
  --includeScenario
\`\`\`

### Run a simulation script

\`\`\`bash
declarative-hex-worlds simulate-scenario \\
  --scenario ./scenario.json \\
  --script ./simulation.script.json \\
  --rounds 10
\`\`\`

### Emit coverage ledger

\`\`\`bash
declarative-hex-worlds coverage \\
  --checksPassed \\
  --outJson docs/release-readiness.json \\
  --outMarkdown docs/release-readiness.md
\`\`\`

## Safe output paths

Every \`--out*\` flag goes through \`safeResolveOutput\` ([PRD C1](https://github.com/jbcom/declarative-hex-worlds/blob/main/docs/PRD/1.0.md#c1)). Paths that escape the current working directory throw before any write happens. \`extract\` refuses to wipe a non-empty destination unless \`--force\` is passed.

## Errors

CLI errors are \`GameboardCliError\` instances ([PRD D2](https://github.com/jbcom/declarative-hex-worlds/blob/main/docs/PRD/1.0.md#d2)). The library's error taxonomy is documented in the [errors reference](/reference/errors/).
`;

writeFileSync(outputPath, banner, 'utf8');
console.log(`Wrote ${outputPath}`);
