/**
 * Root export surface for manifests, board plans, selectors, seeded generation,
 * Koota runtime helpers, game-loop integration, and adapter-ready data.
 *
 * @module
 */
export { freeManifest } from './manifest';
export {
  ASSET_CATEGORIES,
  FACTIONS,
  KAYKIT_PACK_VERSION,
  MEDIEVAL_HEXAGON_SCHEMA_VERSION,
  PACK_EDITIONS,
  TEXTURE_SETS,
  UNIT_STYLES,
  createManifestBundle,
  getManifestAsset,
  hasManifestAsset,
  inspectMedievalHexagonManifest,
  manifestAssetRequiresExtra,
  normalizeMedievalHexagonManifest,
  resolveManifestAssetUrl,
  selectManifestAssets,
  validateMedievalHexagonManifest,
} from './manifest';
export type {
  AssetBounds,
  AssetCategory,
  CreateManifestBundleOptions,
  Faction,
  HexCoordinates,
  HexEdgeIndex,
  HexEdgeInput,
  KayKitAttribution,
  ManifestAssetCatalog,
  ManifestAssetSelection,
  ManifestAssetUrlOptions,
  ManifestDuplicatePreference,
  MedievalHexagonManifestInspection,
  MedievalHexagonManifestIssue,
  MedievalHexagonManifestIssueSeverity,
  MedievalHexagonAsset,
  MedievalHexagonManifestBundle,
  MedievalHexagonManifest,
  MedievalHexagonManifestCounts,
  PackEdition,
  SourcePackInfo,
  TextureSet,
  UnitStyle,
  VariantSelection,
  WorldPosition,
} from './manifest';
export {
  analyzeExternalAssetCompatibility,
  externalAssetSpawnOptions,
  recommendExternalAssetFacing,
} from './compatibility';
export type {
  ExternalAssetAnchor,
  ExternalAssetCompatibilityInput,
  ExternalAssetCompatibilityReport,
  ExternalAssetFacingOptions,
  ExternalAssetFacingRecommendation,
  ExternalAssetFootprintKind,
  ExternalAssetForwardAxis,
  ExternalAssetIntendedRole,
  ExternalAssetPlacementRecommendation,
  ExternalAssetSpawnOptionsInput,
  ExternalAssetSuggestedRole,
  ExternalAssetTileCompatibility,
} from './compatibility';
export {
  GAMEBOARD_COVERAGE_SCHEMA_VERSION,
  GAMEBOARD_CURATED_SHOWCASE_ARTIFACTS,
  GAMEBOARD_RELEASE_GATE_COMMANDS,
  createDefaultGameboardCoveragePackageChecks,
  createDefaultGameboardCoverageReferences,
  renderGameboardCoverageMarkdown,
  summarizeGameboardCoverage,
} from './coverage';
export type {
  CoverageGap,
  CoverageGapSeverity,
  GameboardCoverageCheckStatus,
  GameboardCoverageLinkedPath,
  GameboardCoverageManifestSummary,
  GameboardCoveragePackageCheck,
  GameboardCoveragePackageCheckInput,
  GameboardCoveragePathStatusInput,
  GameboardCoverageReference,
  GameboardCoverageReferenceInput,
  GameboardCoverageReport,
  GameboardCoverageReportStatus,
  GameboardCoverageSimpleRpgEvidence,
  GameboardCoverageSimpleRpgEvidenceMode,
  GameboardCoverageStatus,
  GuidePageCoverage,
  SummarizeGameboardCoverageOptions,
  VisualArtifactCoverage,
  VisualArtifactCoverageSource,
} from './coverage';
export {
  GAMEBOARD_INTERACTION_HANDLER_PRESETS,
  createGameboardInteractionHandlerPreset,
  createMarkTargetActorInteractedHandler,
  createRemoveTargetActorHandler,
  createRemoveTargetPlacementHandler,
  executeGameboardInteractionCommand,
  gameboardCommandActions,
  isGameboardInteractionHandlerPreset,
  planGameboardActorTargetCommand,
  previewGameboardInteractionCommand,
} from './commands';
export type {
  CreateGameboardInteractionHandlerPresetOptions,
  GameboardActorTargetCommandOptions,
  GameboardActorTargetCommandPlan,
  GameboardInteractionCommandExecution,
  GameboardInteractionCommandExecutionOptions,
  GameboardInteractionCommandInput,
  GameboardInteractionCommandPreview,
  GameboardInteractionCommandPreviewOptions,
  GameboardInteractionExecutionStatus,
  GameboardInteractionHandler,
  GameboardInteractionHandlerContext,
  GameboardInteractionHandlerEffect,
  GameboardInteractionHandlerMetadata,
  GameboardInteractionHandlerPreset,
  GameboardInteractionHandlerResult,
  GameboardInteractionHandlerStatus,
  MarkTargetActorInteractedHandlerOptions,
  RemoveTargetActorHandlerOptions,
  RemoveTargetPlacementHandlerOptions,
} from './commands';
export {
  dispatchGameboardActorTargetCommand,
  dispatchGameboardInteractionCommand,
  gameboardSystemActions,
  runGameboardActorTargetInteraction,
  runGameboardInteraction,
  runGameboardSystems,
  snapshotGameboardSystemEvent,
  snapshotGameboardSystemEvents,
} from './systems';
export type {
  DispatchGameboardActorTargetCommandResult,
  DispatchGameboardInteractionCommandOptions,
  DispatchGameboardInteractionCommandResult,
  GameboardCommandBlockedEvent,
  GameboardCommandHandledEvent,
  GameboardCommandHandlerRequiredEvent,
  GameboardCommandIgnoredEvent,
  GameboardMovementBlockedEvent,
  GameboardMovementCompletedEvent,
  GameboardMovementRequestedEvent,
  GameboardMovementSteppedEvent,
  GameboardPatrolBlockedEvent,
  GameboardPatrolCompletedEvent,
  GameboardPatrolEventRecord,
  GameboardPatrolMoveRequestedEvent,
  GameboardPatrolWaitingEvent,
  GameboardQuestAdvancedEvent,
  GameboardQuestBlockedEvent,
  GameboardQuestCompletedEvent,
  GameboardInteractionCommandRecord,
  GameboardMovementEventRecord,
  GameboardQuestEventRecord,
  GameboardSystemEvent,
  GameboardSystemEventRecord,
  RunGameboardActorTargetInteractionResult,
  RunGameboardInteractionOptions,
  RunGameboardInteractionResult,
  RunGameboardSystemsOptions,
  RunGameboardSystemsResult,
} from './systems';
export {
  BlockingActorQuery,
  EnemyActorQuery,
  GameboardActor,
  GameboardActorQuery,
  HostileActorQuery,
  InteractiveActorQuery,
  IsBlockingActor,
  IsEnemyActor,
  IsGameboardActor,
  IsHostileActor,
  IsInteractiveActor,
  IsNpcActor,
  IsPlayerActor,
  IsPropActor,
  NpcActorQuery,
  PlayerActorQuery,
  PropActorQuery,
  areGameboardActorsHostile,
  classifyGameboardPlacement,
  createGameboardActorNavigationProfile,
  findGameboardActor,
  findGameboardActorEntity,
  gameboardActorActions,
  gameboardActorBlocksMovement,
  inspectGameboardActorCollision,
  inspectGameboardActorTargets,
  inspectGameboardInteractionTarget,
  inspectGameboardNeighborhood,
  inspectGameboardTile,
  moveGameboardActor,
  planGameboardInteractionCommand,
  readGameboardActors,
  readGameboardActorsForTile,
  registerGameboardActor,
  selectGameboardActors,
  spawnGameboardActor,
  updateGameboardActor,
} from './actors';
export type {
  GameboardActorCollisionProfile,
  GameboardActorCollisionReport,
  GameboardActorKind,
  GameboardActorMetadataValue,
  GameboardActorNavigationOptions,
  GameboardActorRegistrationOptions,
  GameboardActorSelection,
  GameboardActorSelectionOptions,
  GameboardActorSelectionRecord,
  GameboardActorSelectionSort,
  GameboardActorTarget,
  GameboardActorTargetApproach,
  GameboardActorTargetSort,
  GameboardActorTargetingOptions,
  GameboardActorTargetingReport,
  GameboardActorSnapshot,
  GameboardActorValue,
  GameboardNeighborhoodCenter,
  GameboardNeighborhoodInspection,
  GameboardNeighborhoodInspectionOptions,
  GameboardNeighborhoodTileInspection,
  GameboardInteractionIntent,
  GameboardInteractionCommand,
  GameboardInteractionCommandKind,
  GameboardInteractionCommandOptions,
  GameboardInteractionTargetInput,
  GameboardInteractionTargetKind,
  GameboardInteractionTargetOptions,
  GameboardInteractionTargetReport,
  GameboardTileInspection,
  GameboardTileInspectionOptions,
  MoveGameboardActorOptions,
  SpawnGameboardActorOptions,
  UpdateGameboardActorOptions,
} from './actors';
export {
  HEX_DIRECTIONS,
  containsHex,
  coordinatesForShape,
  edgeBetween,
  findHexPath,
  hexDistance,
  hexKey,
  hexLine,
  hexRange,
  hexRing,
  neighbor,
  neighbors,
  normalizeHexRotationSteps,
  oppositeEdge,
  parseHexKey,
  selectSpawnCoordinates,
} from './coordinates';
export type { HexPathOptions, HexPathResult, SpawnCoordinateOptions } from './coordinates';
export {
  KAYKIT_ELEVATION_STEP,
  KAYKIT_HEX_GEOMETRY,
  KAYKIT_HEX_DEPTH,
  KAYKIT_HEX_ROW_SPACING,
  KAYKIT_HEX_SIDE,
  KAYKIT_HEX_WIDTH,
  KayKitHex,
  axialToWorld,
  createGameboardCoordinateSystem,
  createGameboardGrid,
  createHexagonGameboardGrid,
  createRectangleGameboardGrid,
  createSpawnLocations,
  rowSpacingForGeometry,
  worldToAxial,
} from './coordinates';
export type {
  GameboardCoordinateSystem,
  GameboardCoordinateSystemOptions,
  GameboardGridOptions,
  HexagonGridOptions,
  HexGeometry,
  KayKitGameboardGrid,
  RectangleGridOptions,
  SpawnLocation,
  SpawnLocationOptions,
} from './coordinates';
export {
  BASE_TILE_ASSET_IDS,
  COAST_TILE_ASSET_IDS,
  COLORED_UNIT_PARTS,
  EXTRA_TRANSITION_TILE_ASSET_IDS,
  EXTRA_FACTION_BUILDING_KINDS,
  EXTRA_PROP_ASSET_IDS,
  EXTRA_UNIT_STYLES,
  FACTION_BUILDING_KINDS,
  FREE_FACTION_BUILDING_KINDS,
  FREE_PROP_ASSET_IDS,
  NATURE_ASSET_IDS,
  NEUTRAL_STRUCTURE_KINDS,
  NEUTRAL_UNIT_PARTS,
  PROP_ASSET_IDS,
  RIVER_TILE_ASSET_IDS,
  ROAD_TILE_ASSET_IDS,
  coloredUnitAssetId,
  describeKayKitAssetTreatment,
  describeKayKitGuideAssetCoverage,
  describeKayKitGuidePublicApiCoverage,
  describeKayKitGuideRoleCoverage,
  describeKayKitGuideScenario,
  describeKayKitGuideScenarioCoverage,
  factionBuildingAssetId,
  flagAssetId,
  hasKayKitAssetTreatment,
  isFaction,
  isKnownExtraAssetId,
  isTextureSet,
  isUnitStyle,
  listKayKitAssetPublicTreatments,
  listKayKitGuideAssetCoverages,
  listKayKitGuidePublicApiCoverages,
  listKayKitGuideRoleCoverages,
  listKayKitGuideScenarioAssetRenderGroups,
  listKayKitGuideScenarioAssetRenderRequests,
  listKayKitGuideScenarioAssetUsages,
  listKayKitGuideScenarioAssetUsagesForScenario,
  listKayKitGuideScenarioTreatments,
  listKayKitGuideScenarios,
  neutralUnitAssetId,
  renderKayKitGuideScenarioCoverageMarkdown,
  summarizeKayKitGuideCoverage,
  textureFileName,
} from './catalog';
export type {
  BaseTileAssetId,
  CoastTileAssetId,
  ColoredUnitPart,
  ColoredUnitStyle,
  ExtraTransitionTileAssetId,
  ExtraFactionBuildingKind,
  FactionBuildingKind,
  FreeFactionBuildingKind,
  KayKitAssetPublicRole,
  KayKitAssetPublicTreatment,
  KayKitGuideAssetCoverageCounts,
  KayKitGuideAssetCoverage,
  KayKitGuideCoverageSummary,
  KayKitGuidePageCoverage,
  KayKitGuidePublicApiCoverage,
  KayKitGuideRoleCoverage,
  KayKitGuideScenarioAssetRenderGroup,
  KayKitGuideScenarioAssetRenderRequest,
  KayKitGuideScenarioAssetRenderRequestOptions,
  KayKitGuideScenarioAssetUrlResolver,
  KayKitGuideScenarioAssetUsage,
  KayKitGuideScenarioAssetUsageOptions,
  KayKitGuideScenario,
  KayKitGuideScenarioCoverage,
  KayKitGuideScenarioCoverageMarkdownOptions,
  KayKitGuideScenarioEdition,
  KayKitTileAssetId,
  NatureAssetId,
  NeutralStructureKind,
  NeutralUnitPart,
  PropAssetId,
  RiverTileAssetId,
  RoadTileAssetId,
  UnitPart,
} from './catalog';
export {
  GAMEBOARD_SCHEMA_VERSION,
  GameboardBuilder,
  createGameboardBuilder,
  createGameboardPlan,
  createGameboardPlanFromTiles,
  createMedievalHarborBoard,
  getPlacementAsset,
  listPropClusterAssets,
  requiresExtraAsset,
  summarizeGameboardPlan,
} from './gameboard';
export type {
  BuiltInGameboardTerrain,
  BridgeOptions,
  BridgeVariant,
  ConstructionSiteKind,
  ConstructionSiteOptions,
  ElevationRampDirection,
  ElevationRampOptions,
  FenceFortificationSegment,
  FortificationMaterial,
  FortificationOptions,
  FortificationSegment,
  GameboardPlacementKind,
  GameboardPlacementLayer,
  GameboardPlacementSpec,
  GameboardPlan,
  GameboardPlanAssetSummary,
  GameboardPlanFromTilesOptions,
  GameboardPlanOptions,
  GameboardPlanSummary,
  GameboardShape,
  GameboardTerrain,
  GameboardTileSpec,
  HexagonGameboardShape,
  FactionBuildingOptions,
  HarborKind,
  HarborOptions,
  HillVariant,
  HexRotationSteps,
  MedievalHarborBoardOptions,
  MountainStackOptions,
  MountainVariant,
  NaturePlacementOptions,
  NeutralStructureOptions,
  PropClusterKind,
  PropClusterOptions,
  PropClusterPlacement,
  PropPlacementOptions,
  RectangleGameboardShape,
  RiverCrossing,
  RoadSlope,
  ScatterDecorationOptions,
  SettlementBuilding,
  SettlementOptions,
  SiegeProjectileKind,
  SiegeProjectileOptions,
  SummarizeGameboardPlanOptions,
  TileAssetOptions,
  TransitionPlacementOptions,
  UnitPlacementOptions,
  UnitPresetOptions,
  WallFortificationSegment,
} from './gameboard';
export {
  GAMEBOARD_RECIPE_SCHEMA_VERSION,
  applyGameboardRecipeGeneration,
  appendGameboardRecipeSteps,
  applyGameboardRecipe,
  applyRecipeStep,
  createGameboardLayoutArchetypeRegistryFromRecipe,
  createGameboardLayoutArchetypeRegistryFromRecipeGeneration,
  createGameboardPieceRegistryFromRecipe,
  createGameboardPieceRegistryFromRecipeGeneration,
  createGameboardPlanFromRecipe,
  createGameboardRecipe,
  createGameboardRecipeGenerationFillRules,
  inspectGameboardRecipe,
  mergeGameboardRecipes,
  validateGameboardRecipeGeneration,
  validateGameboardRecipe,
} from './recipe';
export type {
  AddConstructionSiteRecipeStep,
  AddFactionBuildingRecipeStep,
  AddBridgeRecipeStep,
  AddElevationRampRecipeStep,
  AddFortificationRecipeStep,
  AddFlagRecipeStep,
  AddForestRecipeStep,
  AddHarborRecipeStep,
  AddHillRecipeStep,
  AddMountainStackRecipeStep,
  AddNatureRecipeStep,
  AddNeutralStructureRecipeStep,
  AddPlacementRecipeStep,
  AddPropClusterRecipeStep,
  AddPropRecipeStep,
  AddRiverPathRecipeStep,
  AddRoadPathRecipeStep,
  AddSiegeProjectileRecipeStep,
  AddTransitionRecipeStep,
  AddUnitPresetRecipeStep,
  AddUnitRecipeStep,
  GameboardRecipe,
  GameboardRecipeGeneration,
  GameboardRecipePlanOptionsOverride,
  GameboardRecipeStep,
  GameboardRecipeValidationConfig,
  GameboardRecipeValidationResult,
  ScatterDecorationsRecipeStep,
  SetCoastEdgesRecipeStep,
  SetElevationRecipeStep,
  SetTerrainRecipeStep,
  SetTextureSetRecipeStep,
  SetTileAssetRecipeStep,
} from './recipe';
export {
  createMedievalGameboardBlueprintScenario,
  createMedievalGameboardWorldFromBlueprint,
  createMedievalGameboardBlueprintPlan,
  createMedievalGameboardBlueprintRecipe,
  createMedievalShowcaseBlueprintRecipe,
  inspectMedievalGameboardBlueprint,
  inspectMedievalGameboardBlueprintScenario,
} from './blueprint';
export type {
  MedievalBiomeFillSpec,
  MedievalGameboardBlueprintInspection,
  MedievalGameboardBlueprintOptions,
  MedievalGameboardBlueprintScenarioInspection,
  MedievalGameboardBlueprintScenarioOptions,
  MedievalHarborSpec,
  MedievalMountainRangeSpec,
  MedievalPropClusterDressingOptions,
  MedievalPropClusterDressingSpec,
  MedievalRiverNetworkSpec,
  MedievalRoadNetworkSpec,
  MedievalTownSpec,
  MedievalTransitionPolicy,
} from './blueprint';
export {
  createGameboardRuntime,
  createGameboardRuntimeFromRecipe,
  createGameboardRuntimeFromScenario,
} from './runtime';
export type {
  CreateGameboardRuntimeInput,
  CreateGameboardRuntimeOptions,
  GameboardActionBundle,
  GameboardActorActionBundle,
  GameboardCommandActionBundle,
  GameboardMovementActionBundle,
  GameboardPatrolActionBundle,
  GameboardQuestActionBundle,
  GameboardRecipeGameRuntime,
  GameboardRuntime,
  GameboardRuntimeSnapshot,
  GameboardRuntimeSnapshotOptions,
  GameboardScenarioGameRuntime,
  GameboardSystemActionBundle,
} from './runtime';
export {
  analyzeHexTileRegistry,
  analyzeTileGeometry,
  applyTileDeclaration,
  createHexTileRegistry,
  createHexTileRegistryFromManifest,
  declareHexTile,
} from './registry';
export type {
  ApplyTileDeclarationOptions,
  HexTileDeclaration,
  HexTileDeclarationInput,
  HexTileRegistry,
  TileAdjacencyRule,
  TileDeclarationRole,
  TileEdgeDeclaration,
  TileGeometryAnalysis,
  TileRegistryAnalysis,
  TileStackRule,
} from './registry';
export {
  createGameboardInteropSnapshotIndex,
  createGameboardInteropSnapshot,
  createGameboardRuntimeInteropSnapshot,
  createGameboardScenarioInteropSnapshot,
  createGameboardSimulationInteropSnapshot,
  createInMemoryGameboardEcs,
  indexGameboardInteropSnapshot,
  mountGameboardInteropSnapshot,
  selectGameboardInteropRelations,
} from './interop';
export type {
  GameboardEcsAdapter,
  GameboardEcsMountResult,
  GameboardEcsRelation,
  GameboardEcsRelationName,
  GameboardAdjacencyRecord,
  GameboardActorPatrolRouteRecord,
  GameboardActorPlacementRecord,
  GameboardActorTileRecord,
  GameboardInteropEntity,
  GameboardInteropEntityKind,
  GameboardInteropOptions,
  GameboardInteropRelationFilter,
  GameboardInteropScenarioRecord,
  GameboardInteropSnapshot,
  GameboardInteropSnapshotIndex,
  GameboardRuntimeInteropOptions,
  GameboardRuntimeInteropState,
  GameboardPatrolRouteRecord,
  GameboardPatrolRouteSegmentRecord,
  GameboardPatrolWaypointRecord,
  GameboardQuestActorReferenceRecord,
  GameboardQuestActorReferenceRole,
  GameboardQuestTileReferenceRecord,
  GameboardQuestTileReferenceRole,
  GameboardScenarioInteropOptions,
  GameboardSimulationInteropOptions,
  GameboardSimulationRelationRecord,
  GameboardSimulationRelationRole,
  GameboardPlacementOccupancyRecord,
  GameboardPlacementTileRecord,
  GameboardSpawnGroupLocationRecord,
  GameboardSpawnGroupRecord,
  GameboardSpawnGroupRouteRecord,
  GameboardSpawnTileRecord,
  InMemoryGameboardEcs,
  InMemoryGameboardEcsEntity,
} from './interop';
export {
  AdjacentTo,
  CoastPlacementQuery,
  DecomposedGameboardTileQuery,
  ExtraPlacementQuery,
  GameboardPlacementQuery,
  GameboardState,
  GameboardTileQuery,
  HarborPlacementQuery,
  HexTileState,
  IsCoastPlacement,
  IsDecorationPlacement,
  IsGameboardPlacement,
  IsGameboardTile,
  IsHarborPlacement,
  IsPropPlacement,
  IsRiverPlacement,
  IsRoadPlacement,
  IsStackedTerrain,
  IsStructurePlacement,
  IsTerrainPlacement,
  IsUnitPlacement,
  PlacementOnTile,
  PlacementOccupiesTile,
  PlacementState,
  RequiresExtraAsset,
  RiverPlacementQuery,
  RoadPlacementQuery,
  StackedTerrainQuery,
  StructurePlacementQuery,
  TerrainPlacementQuery,
  TileConnectivity,
  TileCoordinates,
  TileElevation,
  TileRenderState,
  TileTagList,
  TileTerrain,
  clearGameboardWorld,
  createGameboardWorld,
  findPlacementEntity,
  findTileEntity,
  gameboardActions,
  canOccupyGameboardPlacement,
  inspectGameboardPlacementOccupancy,
  linkAdjacentTiles,
  moveGameboardPlacement,
  readGameboardPlacementOccupancy,
  readGameboardPlacements,
  readGameboardSnapshot,
  readGameboardTiles,
  readPlacementOccupancyForTile,
  readPlacementsForTile,
  removeGameboardPlacement,
  spawnGameboardPlacement,
  spawnGameboardPlan,
  updateGameboardPlacement,
} from './koota';
export type {
  GameboardEntityIndex,
  GameboardPlacementOccupancyGuard,
  GameboardPlacementOccupancyGuardOptions,
  GameboardPlacementOccupancyInspection,
  GameboardPlacementPositionOffset,
  GameboardSnapshot,
  GameboardStateValue,
  HexTileStateValue,
  InspectGameboardPlacementOccupancyOptions,
  PlacementOccupancySnapshot,
  PlacementOccupancyValue,
  PlacementStateValue,
  SpawnGameboardPlacementOptions,
  TileConnectivityValue,
  TileCoordinatesValue,
  TileElevationValue,
  TileRenderStateValue,
  TileTagListValue,
  TileTerrainValue,
  UpdateGameboardPlacementOptions,
} from './koota';
export {
  GAMEBOARD_LAYOUT_ARCHETYPES,
  analyzeGameboardLayoutFill,
  appendGameboardLayoutPlacementsToPlan,
  createGameboardLayoutArchetypeRegistry,
  createGameboardLayoutFillPlacements,
  createGameboardLayoutPlacements,
  inspectGameboardLayoutSites,
  normalizeGameboardLayoutArchetypeRegistry,
  resolveGameboardLayoutArchetype,
  resolveGameboardLayoutCriteria,
  selectGameboardLayoutSites,
  spawnGameboardLayoutFill,
  spawnGameboardLayoutPlacements,
} from './coordinates';
export type {
  BuiltInGameboardLayoutArchetypeId,
  CreateGameboardLayoutArchetypeRegistryOptions,
  GameboardLayoutArchetype,
  GameboardLayoutArchetypeId,
  GameboardLayoutArchetypeInput,
  GameboardLayoutArchetypeRegistry,
  GameboardLayoutArchetypeRegistryInput,
  GameboardLayoutCriteria,
  GameboardLayoutFillAnalysis,
  GameboardLayoutFillOptions,
  GameboardLayoutFillRule,
  GameboardLayoutFillRuleAnalysis,
  GameboardLayoutFootprintInput,
  GameboardLayoutPlacementOptions,
  GameboardLayoutPreference,
  GameboardLayoutRejectedSite,
  GameboardLayoutSiteInspection,
  GameboardLayoutSiteRejection,
  GameboardLayoutSiteRejectionCode,
  GameboardLayoutSite,
  InspectGameboardLayoutSitesOptions,
  ResolvedGameboardLayoutFootprint,
  SelectGameboardLayoutSitesOptions,
} from './coordinates';
export {
  createGameboardNavigation,
  createGameboardOccupancyIndex,
  findGameboardPath,
  planGameboardPatrolRoute,
  planGameboardPatrolRoutes,
  planGameboardSpawnGroups,
  reachableGameboardTiles,
  selectGameboardSpawnLocations,
} from './gameboard';
export type {
  GameboardNavigation,
  GameboardNavigationContext,
  GameboardNavigationPathResult,
  GameboardNavigationProfile,
  GameboardOccupancyIndex,
  GameboardPatrolRouteOptions,
  GameboardPatrolRoutePlan,
  GameboardPatrolRouteRule,
  GameboardPatrolRouteSegment,
  GameboardPatrolRouteSet,
  GameboardPatrolRouteSetOptions,
  GameboardPatrolWaypoint,
  GameboardPatrolWaypointSource,
  GameboardReachableTile,
  GameboardSpawnGroup,
  GameboardSpawnGroupOptions,
  GameboardSpawnGroupPlan,
  GameboardSpawnGroupRoute,
  GameboardSpawnGroupRule,
  GameboardSpawnLocationOptions,
  RequiredGameboardNavigationProfile,
} from './gameboard';
export {
  gameboardPlacementBlocksOccupancy,
  gameboardPlacementFootprintKeys,
  gameboardPlacementOccupancyGroup,
  gameboardPlacementOccupiesTile,
} from './gameboard';
export type {
  GameboardPlacementOccupancyLike,
  GameboardPlacementOccupancyOptions,
} from './gameboard';
export {
  GameboardPatrolAgent,
  GameboardPatrolAgentQuery,
  GameboardPatrolState,
  IsGameboardPatrolAgent,
  advanceGameboardPatrol,
  clearGameboardPatrolAgent,
  gameboardPatrolActions,
  readGameboardPatrolAgents,
  runGameboardPatrolSystem,
  setGameboardPatrolAgent,
} from './patrol';
export type {
  AdvanceGameboardPatrolOptions,
  GameboardPatrolAdvanceResult,
  GameboardPatrolAgentValue,
  GameboardPatrolRouteInput,
  GameboardPatrolSnapshot,
  GameboardPatrolStateValue,
  GameboardPatrolStatus,
  SetGameboardPatrolAgentOptions,
} from './patrol';
export {
  analyzeGameboardPieceRegistry,
  createGameboardLayoutFillRuleFromPieces,
  createGameboardLayoutFillRuleFromPiece,
  createGameboardLayoutFillRulesFromRegistry,
  createGameboardLayoutPlacementsFromPiece,
  createGameboardLayoutPlacementOptionsFromPiece,
  createGameboardPieceRegistry,
  createGameboardPieceRegistryFromCompatibilityReports,
  createGameboardPieceSourceUrlMap,
  declareGameboardPieceFromCompatibility,
  declareGameboardPiecesFromCompatibilityReports,
  declareGameboardPiece,
  inspectGameboardPiecePlacement,
  resolveGameboardPieceSourceUrl,
  selectGameboardPieces,
} from './pieces';
export type {
  AnalyzeGameboardPieceRegistryOptions,
  GameboardPieceCompatibilityBatchOptions,
  GameboardPieceCollectionLayoutRuleOptions,
  GameboardPieceCompatibilityDeclarationOptions,
  GameboardPieceDeclaration,
  GameboardPieceDeclarationInput,
  GameboardPieceLayoutRuleOptions,
  GameboardPiecePlacementInspection,
  GameboardPiecePlacementOptions,
  GameboardPieceRegistry,
  GameboardPieceRegistryAnalysis,
  GameboardPieceRegistryAnalysisCheck,
  GameboardPieceRegistryAnalysisCheckInput,
  GameboardPieceRegistryAnalysisCheckMode,
  GameboardPieceRegistryFillRulesOptions,
  GameboardPieceRegistrySelection,
  GameboardPieceRole,
  GameboardPieceSourceUrlOptions,
} from './pieces';
export {
  ActiveMovementQuery,
  GAMEBOARD_MOVEMENT_PROFILES,
  IsMoving,
  MovementAgent,
  MovementAgentQuery,
  MovementPathState,
  UnitMovementQuery,
  advanceGameboardMovement,
  clearGameboardMovement,
  createGameboardMovementNavigation,
  findGameboardMovementPath,
  gameboardMovementActions,
  reachableGameboardMovementTiles,
  requestGameboardMovement,
  resetGameboardMovementBudget,
  resolveGameboardMovementProfile,
  runGameboardMovementSystem,
  setGameboardMovementAgent,
} from './movement';
export type {
  AdvanceGameboardMovementOptions,
  BuiltInGameboardMovementProfileId,
  GameboardMovementAdvanceResult,
  GameboardMovementOptions,
  GameboardMovementPathRequestOptions,
  GameboardMovementProfile,
  GameboardMovementProfileId,
  GameboardMovementProfileInput,
  GameboardMovementProfileRegistry,
  GameboardMovementRequestResult,
  GameboardMovementStatus,
  MovementAgentValue,
  MovementPathStateValue,
  SetGameboardMovementAgentOptions,
} from './movement';
export {
  ActiveGameboardQuestQuery,
  BlockedGameboardQuestQuery,
  CompletedGameboardQuestQuery,
  GAMEBOARD_QUEST_SCHEMA_VERSION,
  GameboardQuest,
  GameboardQuestQuery,
  IsActiveGameboardQuest,
  IsBlockedGameboardQuest,
  IsCompletedGameboardQuest,
  IsGameboardQuest,
  advanceAllGameboardQuests,
  advanceGameboardQuest,
  createGameboardQuest,
  evaluateGameboardQuestObjective,
  findGameboardQuest,
  findGameboardQuestEntity,
  gameboardQuestActions,
  readGameboardQuests,
  spawnGameboardQuest,
} from './quests';
export type {
  AdvanceGameboardQuestOptions,
  CollisionQuestObjective,
  DefeatActorQuestObjective,
  GameboardQuestCollisionExpectation,
  GameboardQuestDefinition,
  GameboardQuestMetadataValue,
  GameboardQuestObjective,
  GameboardQuestObjectiveBase,
  GameboardQuestObjectiveEvaluation,
  GameboardQuestObjectiveProgress,
  GameboardQuestObjectiveStatus,
  GameboardQuestSnapshot,
  GameboardQuestStatus,
  GameboardQuestValue,
  InteractActorQuestObjective,
  ReachActorQuestObjective,
  ReachTileQuestObjective,
  SpawnGameboardQuestOptions,
} from './quests';
export {
  canPlaceHarborAt,
  canStackAt,
  createSeededGameboardDensityFillRules,
  createSeededGameboardPieceFillRules,
  createSeededGameboardPlan,
  createSeededGameboardWorld,
  inspectSeededGameboardPieceFillSelections,
  inspectSeededGameboardPieceFills,
  projectWorldToGameboardPlan,
  readDecomposedTileSpecs,
  setTileElevation,
  setTileTerrain,
  validateGameboardRules,
} from './rules';
export type {
  GameboardRuleConfig,
  GameboardRuleViolation,
  RuleSeverity,
  SeededGameboardDensityContext,
  SeededGameboardDensityPresetId,
  SeededGameboardDensityRuleOptions,
  SeededGameboardDensityValue,
  SeededGameboardLayoutDensityOptions,
  SeededGameboardOptions,
  InspectSeededGameboardPieceFillsOptions,
  SeededGameboardPieceFillMode,
  SeededGameboardPieceFillInspection,
  SeededGameboardPieceFillOptions,
  SeededGameboardPieceFillSelectionInspection,
} from './rules';
export {
  GAMEBOARD_SCENARIO_SCHEMA_VERSION,
  createGameboardScenario,
  createGameboardWorldFromScenario,
  inspectGameboardScenario,
  resolveGameboardScenarioActors,
  summarizeGameboardScenario,
  validateGameboardScenario,
} from './scenario';
export type {
  CreateGameboardScenarioOptions,
  GameboardScenario,
  GameboardScenarioActor,
  GameboardScenarioActorPatrolAgent,
  GameboardScenarioActorSummary,
  GameboardScenarioAssetSummary,
  GameboardScenarioPatrolRoute,
  GameboardScenarioRuntime,
  GameboardScenarioSummary,
  GameboardScenarioSummaryValidation,
  GameboardScenarioValidationConfig,
  GameboardScenarioValidationResult,
  ResolvedGameboardScenarioActor,
  SummarizeGameboardScenarioOptions,
} from './scenario';
export {
  GAMEBOARD_SCENARIO_SIMULATION_SCHEMA_VERSION,
  GAMEBOARD_SCENARIO_SIMULATION_STEP_ACTIONS,
  assertGameboardScenarioSimulationExpectations,
  createGameboardPatrolSimulationScript,
  createGameboardPatrolSimulationSteps,
  createGameboardScenarioSimulationReport,
  evaluateGameboardScenarioSimulationExpectations,
  inspectGameboardScenarioSimulationScript,
  runGameboardScenarioSimulation,
  runGameboardScenarioSimulationScript,
  validateGameboardScenarioSimulationScript,
} from './simulation';
export type {
  GameboardScenarioSimulationActorTargetCommandStep,
  GameboardScenarioSimulationActorTargetRecord,
  GameboardScenarioSimulationActorTargetsExpectation,
  GameboardScenarioSimulationActorTargetsRecord,
  GameboardScenarioSimulationActorTargetsStep,
  GameboardScenarioSimulationActorRecord,
  GameboardScenarioSimulationActorExpectation,
  GameboardScenarioSimulationCommandExpectation,
  GameboardScenarioSimulationCommandHandlerPreset,
  GameboardScenarioSimulationCommandRecord,
  GameboardScenarioSimulationCommandStep,
  GameboardScenarioSimulationExpectationFailure,
  GameboardScenarioSimulationExpectations,
  GameboardScenarioSimulationMovementExpectation,
  GameboardScenarioSimulationMovementRecord,
  GameboardScenarioSimulationMutationExpectation,
  GameboardScenarioSimulationMutationRecord,
  GameboardScenarioSimulationPatrolExpectation,
  GameboardScenarioSimulationPatrolRecord,
  GameboardScenarioSimulationPlacementRecord,
  GameboardScenarioSimulationPlacementExpectation,
  GameboardScenarioSimulationQuestExpectation,
  GameboardScenarioSimulationQuestRecord,
  GameboardScenarioSimulationRemoveActorStep,
  GameboardScenarioSimulationRemovePlacementStep,
  GameboardScenarioSimulationReport,
  GameboardScenarioSimulationResult,
  GameboardScenarioSimulationRunSystemsStep,
  GameboardScenarioSimulationScript,
  GameboardScenarioSimulationScriptValidationConfig,
  GameboardScenarioSimulationScriptValidationResult,
  GameboardScenarioSimulationSpawnActorStep,
  GameboardScenarioSimulationSpawnPlacementStep,
  GameboardScenarioSimulationStep,
  GameboardScenarioSimulationStepBase,
  GameboardScenarioSimulationStepReport,
  GameboardScenarioSimulationStepResult,
  GameboardScenarioSimulationUpdateActorStep,
  GameboardScenarioSimulationUpdatePlacementStep,
  CreateGameboardPatrolSimulationScriptOptions,
  CreateGameboardPatrolSimulationStepsOptions,
  GameboardPatrolSimulationActorAssignment,
  GameboardPatrolSimulationAssignmentPlan,
  GameboardPatrolSimulationScriptPlan,
  GameboardPatrolSimulationStepsPlan,
  RunGameboardScenarioSimulationOptions,
} from './simulation';
export { canStackInPlan, validateGameboardPlan } from './validation';
export type { GameboardPlanValidationConfig } from './validation';
export {
  COAST_VARIANTS,
  HEX_EDGE_COUNT,
  HEX_ROTATION_RADIANS,
  HEX_ROTATION_STEPS,
  RIVER_VARIANTS,
  ROAD_VARIANTS,
  edgeMask,
  listCoastGuidePermutations,
  listGuideTilePermutations,
  listRiverCrossingGuidePermutations,
  listRiverCurvyGuidePermutations,
  listRiverGuidePermutations,
  listRoadGuidePermutations,
  rotateMask,
  selectCoastVariant,
  selectCoastVariantByLabel,
  selectRiverCrossingVariant,
  selectRiverVariant,
  selectRiverVariantByLabel,
  selectRoadVariant,
  selectRoadVariantByLabel,
} from './selectors';
export type {
  CanonicalVariant,
  GuidePermutationOptions,
  GuideTilePermutation,
  GuideTilePermutationKind,
} from './selectors';
