import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    actors: 'src/actors.ts',
    blueprint: 'src/blueprint.ts',
    catalog: 'src/catalog.ts',
    compatibility: 'src/compatibility.ts',
    commands: 'src/commands.ts',
    coordinates: 'src/coordinates.ts',
    gameboard: 'src/gameboard.ts',
    grid: 'src/grid.ts',
    interop: 'src/interop.ts',
    koota: 'src/koota.ts',
    layout: 'src/layout.ts',
    movement: 'src/movement.ts',
    navigation: 'src/navigation.ts',
    occupancy: 'src/occupancy.ts',
    patrol: 'src/patrol.ts',
    pieces: 'src/pieces.ts',
    projection: 'src/projection.ts',
    quests: 'src/quests.ts',
    recipe: 'src/recipe.ts',
    registry: 'src/registry.ts',
    react: 'src/react.ts',
    'rule-types': 'src/rule-types.ts',
    rules: 'src/rules.ts',
    runtime: 'src/runtime.ts',
    scenario: 'src/scenario.ts',
    selectors: 'src/selectors.ts',
    simulation: 'src/simulation.ts',
    systems: 'src/systems.ts',
    three: 'src/three.ts',
    types: 'src/types.ts',
    validation: 'src/validation.ts',
    'world-rules': 'src/world-rules.ts',
    cli: 'src/cli.ts',
    ingest: 'src/ingest.ts',
    'manifest/free': 'src/manifest/free.ts',
    'manifest/schema': 'src/manifest/schema.ts',
    'examples/blueprint-board-usage': 'examples/blueprint-board-usage.ts',
    'examples/simple-rpg-usage': 'examples/simple-rpg-usage.ts',
  },
  format: ['esm'],
  dts: true,
  sourcemap: true,
  clean: true,
  target: 'es2022',
  // Shared chunks keep Koota trait identities stable when consumers mix package subpaths.
  splitting: true,
  esbuildOptions(options) {
    options.sourcesContent = false;
  },
  external: [
    '@jbcom/medieval-hexagon-gameboard',
    /^@jbcom\/medieval-hexagon-gameboard\//,
    'koota',
    'koota/react',
    'react',
    'three',
  ],
});
